#!/bin/bash
cpus=$(grep "^processor" /proc/cpuinfo | wc -l)

make mrproper -j16

make ARCH=arm q_i_mpcs_defconfig
ARCH=arm 
#make ARCH=arm CROSS_COMPILE=/media/playfulgod/Android1/CM10/prebuilts/gcc/linux-x86/arm/arm-eabi-4.6/arm-eabi/bin/ -j16
#ARCH=arm CROSS_COMPILE="/media/playfulgod/Android1/CM10/prebuilts/gcc/linux-x86/arm/linaro-4.7/bin/arm-eabi-"
ARCH=arm CROSS_COMPILE=/media/playfulgod/Android1/CM10/prebuilt/linux-x86/toolchain/arm-eabi-4.4.3/bin/arm-eabi- make -j16

#${cpus} $@

if [ -f arch/arm/boot/zImage ]; then
	  echo
      echo "Plague has been compiled!!! You can find it in arch/arm/boot/zImage"
	  echo
else
      echo
	  echo "Kernel did not compile, please check for errors!!"
	  echo
fi
